### ISSUE TITLE
ModbusMaster disconnectimpl()

### ISSUE THREAD

**Issue by dpozimski** [kochedykov/jlibmodbus#1]
Hello!

I am using your library for modbus communication. I updated library to the newest version and i had seen that disconnectimpl(); has a wrong implementation. We cannot now close serial port to use it to other purposes.

Just see and compare with previous version of ModbusMaster.java file:
```
    /**
     * this method allows you to implement your own behavior of disconnect method.
     *
     * @throws ModbusIOException
     */
    protected void disconnectImpl() throws ModbusIOException {
        getConnection().open();
    }
```

**Comment by kochedykov** [comment]
Hi! Thank you for your support, I've just fixed this bug.
