### ISSUE TITLE
ModbusSlaveRTU w/ jssc incorrectly times out on large request transaction size

### ISSUE THREAD

**Issue by kkieffer** [kochedykov/jlibmodbus#13]
ModbusSlaveRTU constructor sets the timeout to 10 * the symbol rate, this is hardcoded.  However with the JSSC implementation, the SerialPort.waitBytesWithTimeout is used to read the entire expected transaction on a call to SerialPort.read(byte[] b, ...)

The desired timeout was for a symbol but JSSC wants a timeout for the entire frame (amount to be read).  Thus, for larger frames, or slow baud rates, JSSC will throw a timeout exception.

Issue is fixed by increasing the timeout in ModbusSlaveRTU to the default 1 second timeout.

**Comment by kochedykov** [comment]
Fixed.
