### ISSUE TITLE
maven support

### ISSUE THREAD

**Issue by WolfgangFahl** [kochedykov/jlibmodbus#2]
Vladislav - your library looks promising. I'd love to use it. 
It would be great if it would be "mavenized" and made available on maven central.

**Comment by kochedykov** [comment]
Hello!

I think the same way. I'm going to add maven support after a little while.

Thanks for your feedback!

**Comment by WolfgangFahl** [comment]
Thank you for the positive feedback. I would appreciate if you'd to the maven stuff first before you add more featurs. Currently I get a NoClassDefFound Error and its hard to work around this.

**Comment by WolfgangFahl** [comment]
I am using my fork as a workaround for the time being

**Comment by kochedykov** [comment]
Thank you, I've merged commits.

**Comment by WolfgangFahl** [comment]
at
https://github.com/WolfgangFahl/Mediawiki-Japi
you can find an example of a github project that is available via maven central. 

here are pointers for some instructions

- http://central.sonatype.org/pages/ossrh-guide.html
- http://datumedge.blogspot.de/2012/05/publishing-from-github-to-maven-central.html
- http://central.sonatype.org/pages/apache-maven.html

**Comment by kochedykov** [comment]
All preparations are done and I'm going to promote the first release today.

**Comment by kochedykov** [comment]
Done. I've promoted the first release on oss.sonatype.org. 

<dependency>
  <groupId>com.github.kochedykov</groupId>
  <artifactId>jlibmodbus</artifactId>
  <version>1.2.8.4</version>
</dependency>

**Comment by kochedykov** [comment]
Done. I've promoted the first release on oss.sonatype.org. 

`<dependency>
  <groupId>com.github.kochedykov</groupId>
  <artifactId>jlibmodbus</artifactId>
  <version>1.2.8.4</version>
</dependency>
`
