### ISSUE TITLE
core dump when communicate through modbus RTU on windows 10.

### ISSUE THREAD

**Issue by peterzhang1688** [kochedykov/jlibmodbus#25]
When run the app communicate through Modbus RTU on windows 10, it will be core dump. But same program works fine on the windows 7. The following are captured when run the program. Looks like it related to the jssc plugin.

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000000007110b5db, pid=740, tid=12968
#
# JRE version: Java(TM) SE Runtime Environment (10.0.1+10) (build 10.0.1+10)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (10.0.1+10, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
# Problematic frame:
# C  [jSSC-2.8_x86_64.dll+0xb5db]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  S U M M A R Y ------------

Command Line: -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:52074,suspend=y,server=n -javaagent:C:\Users\rhqua60\.IdeaIC2018.1\system\captureAgent\debugger-agent.jar=file:/C:/Users/rhqua60/AppData/Local/Temp/capture.props -Dfile.encoding=UTF-8 com.Rexnord.App 1 com4 1 1

Host: Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz, 4 cores, 15G,  Windows 10 , 64 bit Build 16299 (10.0.16299.15)
Time: Fri Jun 22 11:43:12 2018 Central Daylight Time elapsed time: 0 seconds (0d 0h 0m 0s)

---------------  T H R E A D  ---------------

Current thread (0x0000020c90753800):  JavaThread "main" [_thread_in_native, id=12968, stack(0x0000005738d00000,0x0000005738e00000)]

Stack: [0x0000005738d00000,0x0000005738e00000],  sp=0x0000005738dff020,  free space=1020k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [jSSC-2.8_x86_64.dll+0xb5db]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  jssc.SerialNativeInterface.openPort(Ljava/lang/String;Z)J+0
j  jssc.SerialPort.openPort()Z+65
j  com.intelligt.modbus.jlibmodbus.serial.SerialPortJSSC.open()V+4
j  com.intelligt.modbus.jlibmodbus.net.ModbusConnectionSerial.openImpl()V+11
j  com.intelligt.modbus.jlibmodbus.net.ModbusConnection.open()V+1
j  com.intelligt.modbus.jlibmodbus.master.ModbusMaster.connectImpl()V+4
j  com.intelligt.modbus.jlibmodbus.master.ModbusMaster.connect()V+8
j  com.Rexnord.App.main([Ljava/lang/String;)V+265
v  ~StubRoutines::call_stub

siginfo: EXCEPTION_ACCESS_VIOLATION (0xc0000005), reading address 0xffffffff8e781aac

Register to memory mapping:

RIP=0x000000007110b5db jSSC-2.8_x86_64.dll
RAX=0xffffffff8e781aac is an unknown value
RBX=0x0000005738dff090 is pointing into the stack for thread: 0x0000020c90753800
RCX=0x00007ffb90fc0024 ntdll.dll
RDX=0x0000000000000000 is an unknown value
RSP=0x0000005738dff020 is pointing into the stack for thread: 0x0000020c90753800
RBP=0x0000005738dff1a0 is pointing into the stack for thread: 0x0000020c90753800
RSI=0x0000020c90753a70 is an unknown value
RDI=0x00000000000005bc is an unknown value
R8 =0x0000005738dfef18 is pointing into the stack for thread: 0x0000020c90753800
R9 =0x0000005738dff010 is pointing into the stack for thread: 0x0000020c90753800
R10=0x0000000000000000 is an unknown value
R11=0x0000000000000246 is an unknown value
R12=0x0000005738dff260 is pointing into the stack for thread: 0x0000020c90753800
R13=0x0000020cb7725990 is an unknown value
R14=0x0000005738dff150 is pointing into the stack for thread: 0x0000020c90753800
R15=0x0000020c90753800 is a thread

Registers:
RAX=0xffffffff8e781aac, RBX=0x0000005738dff090, RCX=0x00007ffb90fc0024, RDX=0x0000000000000000
RSP=0x0000005738dff020, RBP=0x0000005738dff1a0, RSI=0x0000020c90753a70, RDI=0x00000000000005bc
R8 =0x0000005738dfef18, R9 =0x0000005738dff010, R10=0x0000000000000000, R11=0x0000000000000246
R12=0x0000005738dff260, R13=0x0000020cb7725990, R14=0x0000005738dff150, R15=0x0000020c90753800
RIP=0x000000007110b5db, EFLAGS=0x0000000000010206

**Comment by kochedykov** [comment]
I've tested the library on Windows 10 using JSSC 2.8.0 and physical com ports. After 48 hours of continuous tests, I did not get any crash of JRE. Looks like it related to your JRE environment.
