### ISSUE TITLE
Next Release?

### ISSUE THREAD

**Issue by antiquechrono** [kochedykov/jlibmodbus#54]
There hasn't been a release since 2018 but there are changes on master that fix some bugs. Most notably the pom is broken and the ModbusCoils class doesn't actually return the coils. It looks like both of these issues have been corrected but no release was ever created. Any chance of a new release so these issues get fixed?

**Comment by shdk** [comment]
I'm interested too.

**Comment by shdk** [comment]
I'm interested too. @kochedykov

**Comment by kochedykov** [comment]
The new release is coming soon. I was busy with another large project.

**Comment by shdk** [comment]
> 
> 
> The new release is coming soon. I was busy with another large project.

Thanks @kochedykov. I am really looking forward for it.

**Comment by leoandrea7** [comment]
Hi @kochedykov, any news about next release?

**Comment by yongseokleecom** [comment]
I'm also waiting for the release ~!

**Comment by ajb113** [comment]
Hi @kockedykov thanks for providing this library.

Are you still maintaining this project? I'm running into the issue that was fixed in https://github.com/kochedykov/jlibmodbus/commit/63d142928f9dc61f496f19df83c97a224f734145 so am also interested in a new release.

**Comment by AlexGuironnetRTE** [comment]
Hello,

I'd be interested too, issue https://github.com/kochedykov/jlibmodbus/issues/24 means we have to add the jar with the fix version to our repo as our Gradle build fails with the current release.
Is there anything we can do to help with the release ?

Thanks for providing this library !

**Comment by shdk** [comment]
@kochedykov, can you release a new version including the last commits, please?

**Comment by kochedykov** [comment]
Done!
