### ISSUE TITLE
support negative value for register

### ISSUE THREAD

**Issue by neutralhy** [kochedykov/jlibmodbus#86]
Currently, checkRegisterValue ranges from 0 to MAX_REGISTER_VALUE,
but negative values can also be handled.

So I suggest code like this.

: at Modbus.java

    static public boolean checkRegisterValue(int value) {
        return checkRange(value, Short.MIN_VALUE, Modbus.MAX_REGISTER_VALUE);
    }

**Comment by kochedykov** [comment]
Fixed with commit 32a1ad7a2ca697fef4bd5487a96de4d747370b54
