### ISSUE TITLE
Inconsistency between the source code and the published JAR results in RTU access timeout

### ISSUE THREAD

**Issue by double-7** [kochedykov/jlibmodbus#88]
1. When I use RTU to access data, I always report an error：
<img width="812" alt="f48a5489f55067435eae5329e767519" src="https://user-images.githubusercontent.com/24646801/220866621-656020ee-e480-48fc-81a1-251eb7af1988.png">

2. I found that the problem was caused by the inconsistency between the released JAR package and the source code

**download source**
-  https://sourceforge.net/projects/jlibmodbus/
-  https://mvnrepository.com/
The jar I downloaded from the above two websites

**jar:**
![image](https://user-images.githubusercontent.com/24646801/220867573-c6e64b4a-bb04-46ae-9d57-5e8e23d5da8a.png)

**source code:**
https://github.com/kochedykov/jlibmodbus/blob/c6f663bbc3d1d8e076d418d7b974bec8bc8e551a/src/com/intelligt/modbus/jlibmodbus/serial/SerialPortJSerialComm.java#L77

**jSerialComm**
`static final public int TIMEOUT_READ_BLOCKING = 0x00000010;`
https://github.com/Fazecast/jSerialComm/blob/bde01eff9b668bd35ff05401f8470b70da9ae910/src/main/java/com/fazecast/jSerialComm/SerialPort.java#L78

**Comment by kochedykov** [comment]
Fixed. Please use the latest release 1.2.9.9.
