### ISSUE TITLE
No pom for latest release (1.2.9.9)

### ISSUE THREAD

**Issue by ben-fussell** [kochedykov/jlibmodbus#94]
@kochedykov Did the release process change since 1.2.9.7? In the [maven repo](https://repo.maven.apache.org/maven2/com/intelligt/modbus/jlibmodbus/), 1.2.9.7 is the last version that has a pom file, and I'm getting errors loading this resource after trying to upgrade to 1.2.9.9.

**Comment by kochedykov** [comment]
Hi! It's my fault. I'll fix it today.

**Comment by kochedykov** [comment]
Fixed. Look at the release 1.2.9.10.
