### ISSUE TITLE
Possible update jssc version?

### ISSUE THREAD

**Issue by PersikLopa** [kochedykov/jlibmodbus#96]
jssc version 2.8.0 has problems when running on jdk11+ on win x64 platform:

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000000007110b5db, pid=8248, tid=4072
#
# JRE version: OpenJDK Runtime Environment (17.0.5+8) (build 17.0.5+8-LTS)
# Java VM: OpenJDK 64-Bit Server VM (17.0.5+8-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [jSSC-2.8_x86_64.dll+0xb5db]
```

When updating the jssc version (I'm using 2.9.2, https://github.com/java-native/jssc ) there was no problem at work
It would be possible to redefine the jssc version in my pom file, but I can't do this because the package name has been changed.
Perhaps it is worth updating the jssc version in the project to a newer one?

**Comment by kochedykov** [comment]
Done. Released version 1.2.9.11.
